# Generated by Django 4.2.2 on 2023-06-11 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, help_text='Date and time of Order creation')),
                ('commentary', models.TextField(blank=True, help_text='Commentary to an Order', verbose_name='Commentary')),
                ('paid_amount', models.IntegerField(help_text='Amount of money client paid', verbose_name='Paid Amount')),
                ('is_takeaway', models.BooleanField(help_text='Is Order been taken as a takeaway', verbose_name='Takeaway')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.SmallIntegerField(help_text='Amount of product ordered')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.order')),
            ],
        ),
    ]
