services:
  frontend-dev:
    container_name: frontend-dev
    build:
      context: frontend
      dockerfile: Dockerfile.dev
      target: development
    command: npm run dev
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    networks:
      - dev
    depends_on:
      - server-dev

  server-dev:
    container_name: server-dev
    build:
      context: server
      dockerfile: Dockerfile.dev
      target: development
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./server:/server
    ports:
      - 8000:8000
    env_file:
      - ./server/.env.local
    networks:
      - dev
    depends_on:
      - postgres-dev

  postgres-dev:
    container_name: tabletamer-db-dev
    image: postgres
    volumes:
      - postgres-data:/var/lib/posgresql/data
    networks:
      - dev
    environment:
      - POSTGRES_DB=tabletamer
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  bar-department-dev:
    container_name: bar-department-dev
    build:
      context: department-server
      dockerfile: Dockerfile.dev
      target: builder
    networks:
      - dev
    command: python -u dev.py
    ports:
      - 5001:80

  brazier-department-dev:
    container_name: brazier-department-dev
    build:
      context: department-server
      dockerfile: Dockerfile.dev
      target: builder
    networks:
      - dev
    command: python -u dev.py
    ports:
      - 5002:80

  kitchen-department-dev:
    container_name: kitchen-department-dev
    build:
      context: department-server
      dockerfile: Dockerfile.dev
      target: builder
    networks:
      - dev
    command: python -u dev.py
    ports:
      - 5003:80

volumes:
  postgres-data:

networks:
  dev:
