# Generated by Django 4.2.1 on 2023-05-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Department name', max_length=64, unique=True, verbose_name='Department')),
                ('title_ukr', models.CharField(help_text='Department name in Ukrainian', max_length=64, unique=True, verbose_name='Department (UKR)')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
    ]
