# Generated by Django 4.2.1 on 2023-06-05 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Department name', max_length=64, unique=True, verbose_name='Department')),
                ('department_url', models.URLField(default='', help_text='URL of a department to send a receipt', verbose_name='Department URL')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
    ]
